name: pokemon_proxy
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.1.4
  dart_frog: ^0.2.1
  dart_frog_cli: ^0.2.1
  http: ^0.13.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
